In [106]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('matches.csv')
df = df.drop('winner', axis=1)  # Keep only features

# Encode all string columns
for col in df.columns:
    if df[col].dtype == 'object':  # If column is string type
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

X = df
y = pd.read_csv('matches.csv')['winner']
y = LabelEncoder().fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=300, max_depth=10)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=300)

In [107]:
df.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [108]:
df = df[['team1', 'team2', 'toss_winner', 'venue']]

In [109]:
df.head()

   team1  team2  toss_winner  venue
0     14     13           13     28
1      8     11           11     21
2      4      7            7     31
3     11      5            5     13
4     13      3           13     17

In [110]:
df.isnull().sum()
df = df.dropna()

In [111]:
df.isnull().sum()

team1          0
team2          0
toss_winner    0
venue          0
dtype: int64

In [112]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['team1'] = le.fit_transform(df['team1'])
df['team2'] = le.fit_transform(df['team2'])
df['toss_winner'] = le.fit_transform(df['toss_winner'])
df['venue'] = le.fit_transform(df['venue'])

# df no longer contains 'winner' after subsetting columns.
# Keep winner in df_original and encode there for y:
# y = LabelEncoder().fit_transform(df_original['winner'])

In [113]:
df.head()

   team1  team2  toss_winner  venue
0     14     13           13     28
1      8     11           11     21
2      4      7            7     31
3     11      5            5     13
4     13      3           13     17

In [114]:
import pandas as pd

# Load the full dataset to access 'winner'
df = pd.read_csv('matches.csv')

# Step 1: Select ONLY required columns
X = df[['team1', 'team2', 'toss_winner', 'venue']].copy()
y = df['winner'].copy()

# Step 2: Encode
for col in X.columns:
    X[col] = X[col].astype('category').cat.codes

y = y.astype('category').cat.codes
# Step 3: VERIFY (CRITICAL)
print(X.dtypes)
print(X.head())

team1          int8
team2          int8
toss_winner    int8
venue          int8
dtype: object
   team1  team2  toss_winner  venue
0     14     13           13     28
1      8     11           11     21
2      4      7            7     31
3     11      5            5     13
4     13      3           13     17

In [115]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [116]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=300, max_depth=10)

model.fit(X_train, y_train)
print(X.head())
print(X_train.head())

   team1  team2  toss_winner  venue
0     14     13           13     28
1      8     11           11     21
2      4      7            7     31
3     11      5            5     13
4     13      3           13     17
     team1  team2  toss_winner  venue
670     13      0            0     21
146      1      8            1     38
573     13     10           13     21
346      0      7            0     20
238      5      9            5      5

In [117]:
y_pred = model.predict(X_test)

In [118]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.4473684210526316

In [119]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.2565789473684211

c:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [120]:
import pickle
pickle.dump(model, open("model.pkl", "wb"))

In [130]:
model = pickle.load(open("model.pkl", "rb"))

In [131]:
import numpy as np

sample = np.array([[14, 13, 13, 28]])
prediction = model.predict(sample)

print("Predicted winner:", prediction)

Predicted winner: [14]

c:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [132]:
print(df['team1'].unique())

['Sunrisers Hyderabad' 'Mumbai Indians' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Royal Challengers Bangalore'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kings XI Punjab'
 'Chennai Super Kings' 'Rajasthan Royals' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants'
 'Delhi Capitals']

In [133]:
df_original = pd.read_csv("matches.csv")

In [134]:
print(df_original['team1'].unique())

['Sunrisers Hyderabad' 'Mumbai Indians' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Royal Challengers Bangalore'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kings XI Punjab'
 'Chennai Super Kings' 'Rajasthan Royals' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants'
 'Delhi Capitals']

In [135]:
import pandas as pd
df_original = pd.read_csv("matches.csv")
print(df_original['venue'].unique())

['Rajiv Gandhi International Stadium, Uppal'
 'Maharashtra Cricket Association Stadium'
 'Saurashtra Cricket Association Stadium' 'Holkar Cricket Stadium'
 'M Chinnaswamy Stadium' 'Wankhede Stadium' 'Eden Gardens'
 'Feroz Shah Kotla' 'Punjab Cricket Association IS Bindra Stadium, Mohali'
 'Green Park' 'Punjab Cricket Association Stadium, Mohali'
 'Sawai Mansingh Stadium' 'MA Chidambaram Stadium, Chepauk'
 'Dr DY Patil Sports Academy' 'Newlands' "St George's Park" 'Kingsmead'
 'SuperSport Park' 'Buffalo Park' 'New Wanderers Stadium'
 'De Beers Diamond Oval' 'OUTsurance Oval' 'Brabourne Stadium'
 'Sardar Patel Stadium, Motera' 'Barabati Stadium'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Himachal Pradesh Cricket Association Stadium' 'Nehru Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Subrata Roy Sahara Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'JSCA International Stadium Complex' 'Sheikh Zayed Stadium'
 'Sharjah Cricket Stadium' 'Dubai International Cricket Stadium'
 'M. A. Chidambaram Stadium' 'Feroz Shah Kotla Ground'
 'M. Chinnaswamy Stadium' 'Rajiv Gandhi Intl. Cricket Stadium'
 'IS Bindra Stadium' 'ACA-VDCA Stadium']

In [136]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load your data
df = pd.read_csv('matches.csv')

# Separate features (X) and target (y)
X = df.drop('winner', axis=1)  # All columns except target
y = df['winner']  # Only the target column

# Now split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [137]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=300, max_depth=10)

model.fit(X_train, y_train)

ValueError: could not convert string to float: 'IPL-2010'

In [ ]:
print(X.head())